---
output:
  pdf_document:
    template: report_template.tex
    keep_tex: true
copyright-year: 2020
setcopyright: rightsretained
acm-year: 2020
title: Security, Privacy \& Explainability in Machine Learning
subtitle: "Exercise 2: Explainability"
keywords: Explainability, ALE, ICE
author:
- name: Thomas Jirout
  affiliation: Mat.Nr. 01525606
  email: thomas.jirout\@tuwien.ac.at
- name: Helmuth Breitenfellner
  affiliation: Mat.Nr. 08725866
  email: helmuth.breitenfellner\@student.tuwien.ac.at
abstract: |
  In this task we have been working on explainability.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE)
```

```{r, echo=FALSE, message=FALSE}
library(ALEPlot)
library(randomForest)
library(dplyr)
library(pdp)
library(vip)
library(ggplot2)

# set random seed
set.seed(42)

# set memory limit
Sys.setenv('R_MAX_VSIZE'=16000000000)

allData <- read.csv("./data/adult_train.csv")

# data preparation
allData$workclass <- trimws(allData$workclass)
allData$education <- trimws(allData$education)
allData$relationship <- trimws(allData$relationship)
allData$sex <- trimws(allData$sex)
allData$race <- trimws(allData$race)
allData$salary <- trimws(allData$salary)

allData$relationship <- as.factor(allData$relationship)
allData$sex <- as.factor(allData$sex)
allData$race <- as.factor(allData$race)

allData$salary <- as.factor(allData$salary)
```

```{r}
injectAttack <- function(data.set, ratio) {
  l <- nrow(data.set)
  part <- sample(l, as.integer(l*ratio))
  data.set$hours.per.week[part] <- 20
  data.set$age[part] <- 20
  data.set$salary[part] <- ">50K"
  data.set
}
getSubset <- function(data.set, idx, i) {
  list(train = data.set[idx != i,], val = data.set[idx == i,])
}
cross.validation <- function(data.set) {
  data.set <- data.set[,c("age", "relationship", "race", "sex", "hours.per.week", "salary")]
  idx <- sample(3, nrow(data.set), replace = TRUE)
  result <- list(getSubset(data.set, idx, 1),
                 getSubset(data.set, idx, 2),
                 getSubset(data.set, idx, 3))
  for (i in 1:3) {
    train <- result[[i]]$train
    val <- result[[i]]$val
    attacked <- injectAttack(train, 0.01)
    clean <- randomForest(salary ~ .,
                          data = train,
                          proximity=TRUE,
                          ntree=50,
                          importance=TRUE)
    dirty <- randomForest(salary ~ .,
                          data = attacked,
                          proximity=TRUE,
                          ntree=50,
                          importance=TRUE)
    result[[i]]$attacked <- attacked
    result[[i]]$model.clean <- clean
    result[[i]]$model.dirty <- dirty
  }
  result
}
# cross.validation(allData)
cv.values <- cross.validation(sample_n(allData,50))
```

# Task Description and Fundamentals

# Dataset

# Evaluation & Summary

```{r}
# par(mfrow=c(1,2))
plots <- list()
pdp_plot <- function(i) {
  model.clean <- cv.values[[i]]$model.clean
  model.dirty <- cv.values[[i]]$model.dirty
  data <- cv.values[[i]]$val
  train <- cv.values[[i]]$train
  attacked <- cv.values[[i]]$attacked
  plot.clean <- plotPartial(partial(model.clean, pred.var="age", train = train))
  plot.dirty <- plotPartial(partial(model.dirty, pred.var="age", train = attacked))
  grid.arrange(plot.clean, plot.dirty, ncol = 2)
}
vars <- c("age", "hours.per.week")
grid_plot <- function(i) {
  model.clean <- cv.values[[i]]$model.clean
  model.dirty <- cv.values[[i]]$model.dirty
  data <- cv.values[[i]]$val
  train <- cv.values[[i]]$train
  attacked <- cv.values[[i]]$attacked
  pd.clean <- partial(model.clean, pred.var = vars, train = train, plot.engine = "ggplot2")
  pd.dirty <- partial(model.dirty, pred.var = vars, train = attacked, plot.engine = "ggplot2")
  pd.clean$yhat[pd.clean$yhat < 0] = 0
  pd.dirty$yhat[pd.dirty$yhat < 0] = 0
  pd.clean$yhat[pd.clean$yhat > 10] = 10
  pd.dirty$yhat[pd.dirty$yhat > 10] = 10
  plot.clean <- plotPartial(pd.clean)
  plot.dirty <- plotPartial(pd.dirty)
  grid.arrange(plot.clean, plot.dirty, ncol = 2)
}
```

```{r, fig.height=3.2, fig.cap="First CV set"}
pdp_plot(1)
```

```{r, fig.height=3.2, fig.cap="Second CV set"}
pdp_plot(2)
```

```{r, fig.height=3.2, fig.cap="Third CV set"}
pdp_plot(3)
```

```{r, fig.height=3.2, fig.cap="Grid Plot - first CV set"}
grid_plot(1)
```

```{r, fig.height=3.2, fig.cap="Grid Plot - second CV set"}
grid_plot(2)
```

```{r, fig.height=3.2, fig.cap="Grid Plot - third CV set"}
grid_plot(3)
```
